export default `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCf8H//VEs5kSUnJo5e2emJo6/y
NdGCDtRasYlVWpddRaLVv4BIOCh8fRd0u10eACHUjDPypvCWyd7whv553hCaEmxU
FxhlHO0OVeOgXcldRzr95VHZxz8vsWEzWZYaWbfiYYmSzWQEQJaFZgze8T9RTGun
Re24Y8ktZ+3+gYixIwIDAQAB
-----END PUBLIC KEY-----`;
